### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by huyu1994** [geasyheart/flask-invoke#1]
invoke和finder有什么区别

**Comment by geasyheart** [comment]
finder类似zookeeper,它实现的主要功能在于服务的注册与发现
invoke类似调用层，比如有多个服务（社区服务、用户服务等），他们之间的调用方式可以通过HTTP或者RPC的方式，如果通过http的方式，那么一种简单简单做法要在服务启动的时候向finder发送请求获取指定服务的运行地址，然后发送请求，每个请求都可以包装一下，例如实现:
```python
user_service.login(<username>,<password>)
```
而我的这个invoke就是封装了finder以及各个服务的调用（自己封装一层SDK，可以给其他人调用），当然你也可以借助现成的框架，例如Grpc、Thrift实现，写起来至少要比自己还要封装下SDK更为方便，所以最后想说：这两个实际和flask本身没有任何关系，所以不要误解了。

**Comment by huyu1994** [comment]
明白了
